apiVersion: v1
kind: Secret
metadata:
  name: celeryworker-tpl-admin-backend-secret
  namespace: ${NAMESPACE:-app-platform-dev}
  labels:
    app: celeryworker-tpl-admin-backend
    component: celery-worker
    backend: tpl-admin-backend
type: Opaque
stringData:
  CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
  CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
