apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: ${NAMESPACE:-app-platform-dev}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${HARBOR_DOCKER_CONFIG_JSON}
