apiVersion: v1
kind: Secret
metadata:
  name: nodebullworker-tpl-web-backend-secret
  namespace: ${NAMESPACE:-app-platform-dev}
  labels:
    app: nodebullworker-tpl-web-backend
    component: node-bull-worker
    backend: tpl-web-backend
type: Opaque
stringData: {}
