apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celeryworker-tpl-admin-backend-pvc
  namespace: ${NAMESPACE:-app-platform-dev}
  labels:
    app: celeryworker-tpl-admin-backend
    component: celery-worker
    backend: tpl-admin-backend
spec:
  accessModes:
    - ${PVC_ACCESS_MODE:-ReadWriteOnce}
  storageClassName: ${PVC_STORAGE_CLASS:-local-path}
  resources:
    requests:
      storage: ${PVC_STORAGE_SIZE:-10Gi}
