apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    app: app-platform
    component: celeryworker-tpl-admin-backend
    environment: ${ENVIRONMENT}
    managed-by: deploy-script
