apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebullworker-tpl-web-backend-pvc
  namespace: ${NAMESPACE:-app-platform-dev}
  labels:
    app: nodebullworker-tpl-web-backend
    component: node-bull-worker
    backend: tpl-web-backend
spec:
  accessModes:
    - ${PVC_ACCESS_MODE:-ReadWriteOnce}
  storageClassName: ${PVC_STORAGE_CLASS:-local-path}
  resources:
    requests:
      storage: ${PVC_STORAGE_SIZE:-10Gi}
